### __Paquetes__

In [163]:
import Tools as t
import pandas as pd
import numpy as np
from notion_client import Client
from datetime import datetime
import re
import emoji
import tkinter as tk
from tkinter import filedialog
from tkinter import simpledialog

import sys
sys.path.append('c:/Users/tomas/Documents/Programación/Universidad/Patricionog/Datos/Paquetes/')
import Foragio as fg
import Excelio as ex
import Framio as fr
import Stringio as st
import Listio as ls
import Graphio as gr
import Notio as nt
import Highlightio as hg

### __Variables globales__

In [164]:
# Páginas.

Help_Valid_Txt = 'www.exhurbia.com/valid-txt'

In [165]:
# Notion.

Token = '***TOKEN_REMOVIDO***'
Client = Client(auth=Token)

### __Opciones y mensajes interactivos__

##### 0. Mensajes predefinidos

In [166]:
Dicotomic_Options = [True, False]
Message_Request_Number = "Introducí el número de tu elección:"
Message_Selected_Option = "Opción seleccionada:"
Message_Invalid_Option = "Opción no válida. La elección debe ser un valor entre 1 y"
Message_Invalid_Input = "Entrada no válida. Por favor introduce un número."

##### 1. Textos en el explorador para seleccionar File

In [167]:
Explorer_Input_Title = 'Seleccioná el recorte con tus notas'
Filetypes_Description_Input = ['Archivos TXT']
Filetypes_Extension_Input = ['txt']

Filetypes_Tuples_Input = []

# Crear tuplas.
for Index, Filetype in enumerate(Filetypes_Description_Input):
    Tuple = (Filetype, f'*.{Filetypes_Extension_Input[Index]}*')
    Filetypes_Tuples_Input.append(Tuple)

##### 2.1. Usar formato de output por defecto o no

In [168]:
Default_Output_Format_Options = Dicotomic_Options
Default_Output_Format_Messages = ["¿Querés usar la configuración de salida por defecto?",
                                Message_Request_Number,
                                Message_Selected_Option,
                                f"{Message_Invalid_Option} {len(Default_Output_Format_Options)}.",
                                Message_Invalid_Input]

##### 2.2. Formato de output

In [169]:
Output_Format_Options = ['pdf', 'docx', 'doc', 'odt', 'csv', 'xlsx', 'xls', 'txt', 'Exportar a Notion', 'Exportar a Evernote']
Output_Format_Messages = ["Elegí el formato de salida:",
                          Message_Request_Number,
                          Message_Selected_Option,
                          f"{Message_Invalid_Option} {len(Output_Format_Options)}.",
                          Message_Invalid_Input]

##### 3.1. Partir o no el output

In [170]:
Output_Partition_Options = Dicotomic_Options
Output_Partition_Messages = ["¿Querés que salgan varios archivos de salida?",
                                Message_Request_Number,
                                Message_Selected_Option,
                                f"{Message_Invalid_Option} {len(Output_Partition_Options)}.",
                                Message_Invalid_Input]

##### 3.2. Usar partición del output por defecto o no

In [171]:
Default_Output_Partition_Options = Dicotomic_Options
Default_Output_Partition_Messages = ["¿Querés usar la configuración de partición del archivo de salida por defecto?",
                                Message_Request_Number,
                                Message_Selected_Option,
                                f"{Message_Invalid_Option} {len(Default_Output_Partition_Options)}.",
                                Message_Invalid_Input]

##### 3.3. Criterio para partición del output

In [172]:
Output_Partition_Criterion_Options = ['Por autor', 'Por libro', 'Por año', 'Por mes', 'Por día']
Output_Partition_Criterion_Messages = ["Elegí el criterio de partición de archivos:",
                          Message_Request_Number,
                          Message_Selected_Option,
                          f"{Message_Invalid_Option} {len(Output_Partition_Criterion_Options)}.",
                          Message_Invalid_Input]

##### 4.1. Usar ubicación del output por defecto o no

In [173]:
Default_Output_Path_Options = Dicotomic_Options
Default_Output_Path_Messages = ["¿Querés usar la configuración de guardado del archivo de salida por defecto?",
                                Message_Request_Number,
                                Message_Selected_Option,
                                f"{Message_Invalid_Option} {len(Default_Output_Path_Options)}.",
                                Message_Invalid_Input]

##### 4.2. Textos en el explorador para seleccionar carpeta del output

In [174]:
Explorer_Output_Title = 'Seleccioná la carpeta y el nombre del archivo final'
Filetypes_Description_Output = ['Archivos PDF', 'Archivos Word', 'Archivos Word', 'Archivos LibreOffice Writer', 'Archivos CSV', 'Archivos Excel', 'Archivos Excel', 'Archivos TXT']
Filetypes_Extension_Output = ['pdf', 'docx', 'doc', 'odt', 'csv', 'xlsx', 'xls', 'txt']

Filetypes_Tuples_Output = []

# Crear tuplas.
for Index, Filetype in enumerate(Filetypes_Description_Output):
    Tuple = (Filetype, f'*.{Filetypes_Extension_Output[Index]}*')
    Filetypes_Tuples_Output.append(Tuple)

##### 5. Mensaje de selección de usar configuración de Matchs por defecto o no

In [175]:
Default_Match_Options = Dicotomic_Options
Default_Match_Messages = ["¿Querés usar la configuración de matchs y agrupamiento de highlights por defecto?",
                                Message_Request_Number,
                                Message_Selected_Option,
                                f"{Message_Invalid_Option} {len(Default_Match_Options)}.",
                                Message_Invalid_Input]

##### 6. Mensaje de selección de usar configuración de Proccesing por defecto o no

In [176]:
Default_Processing_Options = Dicotomic_Options
Default_Processing_Messages = ["¿Querés usar la configuración de procesamiento de los highlights por defecto?",
                                Message_Request_Number,
                                Message_Selected_Option,
                                f"{Message_Invalid_Option} {len(Default_Processing_Options)}.",
                                Message_Invalid_Input]

##### 7.1.  Mensaje de selección de usar configuración de estilo de Block por defecto o no

In [177]:
Default_Block_Style_Options = Dicotomic_Options
Default_Block_Style_Messages = ["¿Querés usar la configuración de estilo de los highlights por defecto?",
                                Message_Request_Number,
                                Message_Selected_Option,
                                f"{Message_Invalid_Option} {len(Default_Block_Style_Options)}.",
                                Message_Invalid_Input]

##### 7.2. Estilos del bloque

In [178]:
Block_Style_Options = [1, 2, 3, 4, 5, 6]
Block_Style_Messages = ["Elegí el estilo y la fuente de cada bloque:",
                          Message_Request_Number,
                          Message_Selected_Option,
                          f"{Message_Invalid_Option} {len(Block_Style_Options)}.",
                          Message_Invalid_Input]

##### 7.3. Estilo de fuente del highlight

In [179]:
Highlight_Font_Style_Options = ['Normal', 'Negrita', 'Cursiva', 'Negrita y cursiva']
Highlight_Font_Style_Messages = ["Elegí el estilo de los highlights:",
                          Message_Request_Number,
                          Message_Selected_Option,
                          f"{Message_Invalid_Option} {len(Highlight_Font_Style_Options)}.",
                          Message_Invalid_Input]

##### 7.4. Estilo de fuente de la subline

In [180]:
Subline_Font_Style_Options = ['Normal', 'Negrita', 'Cursiva', 'Negrita y cursiva']
Subline_Font_Style_Messages = ["Elegí el estilo de las sublines:",
                          Message_Request_Number,
                          Message_Selected_Option,
                          f"{Message_Invalid_Option} {len(Subline_Font_Style_Options)}.",
                          Message_Invalid_Input]

##### 7.5. Fuente del highlight

In [181]:
# Esta tiene que ser una lista personalizada de fuentes. 
# Supongo se hace en la parte front.

Highlight_Font_Message = 'Ingresá la fuente del highlight.'

##### 7.6. Fuente de la subline

In [182]:
# Esta tiene que ser una lista personalizada de fuentes. 
# Supongo se hace en la parte front.

Subline_Font_Message = 'Ingresá la fuente de la subline:'

##### 7.7. Color de fuente del highlight

In [183]:
# Esta tiene que ser una lista personalizada de colores. 
# Supongo se hace en la parte front.

Highlight_Color_Message = 'Ingresá el color del texto de la subline:'

##### 7.8. Color de fuente de la subline

In [184]:
# Esta tiene que ser una lista personalizada de colores. 
# Supongo se hace en la parte front.

Subline_Color_Message = 'Ingresá el color del texto de la subline:'

##### 7.9. Tamaño de fuente del highlight

In [185]:
# Lo ingresa numéricamente el usuario.
Highlight_Font_Size_Message = 'Ingresá el tamaño del texto del highlight:'

##### 7.10. Tamaño de fuente del subline

In [186]:
# Lo ingresa numéricamente el usuario.
Subline_Font_Size_Message = 'Ingresá el tamaño del texto de la subline:'

##### 7.11. Alineación del highlight

In [187]:
Highlight_Align_Options = ['Izquierda', 'Derecha', 'Centro', 'Justificada']
Highlight_Align_Messages = ["Elegí la alineación de los highlights:",
                          Message_Request_Number,
                          Message_Selected_Option,
                          f"{Message_Invalid_Option} {len(Highlight_Align_Options)}.",
                          Message_Invalid_Input]

##### 7.12. Alineación de la subline

In [188]:
Subline_Align_Options = ['Izquierda', 'Derecha', 'Centro', 'Justificada']
Subline_Align_Messages = ["Elegí la alineación de las sublines:",
                          Message_Request_Number,
                          Message_Selected_Option,
                          f"{Message_Invalid_Option} {len(Subline_Align_Options)}.",
                          Message_Invalid_Input]

##### 8.1. Usar la configuración de nombrado de output por defecto o no

In [189]:
Default_Naming_Options = Dicotomic_Options
Default_Naming_Messages = ["¿Querés usar la configuración de nombrado de archivos por defecto?",
                                Message_Request_Number,
                                Message_Selected_Option,
                                f"{Message_Invalid_Option} {len(Default_Naming_Options)}.",
                                Message_Invalid_Input]

##### 8.2. En caso de ser solo uno, nombrar archivo

In [190]:
# Lo ingresa el usuario.
Naming_Message = 'Ingresá el nombre del archivo final que se guardará en la carpeta seleccionada:'

### __Etapa 1. Pantalla de inicio (P_Start)__

In [191]:
# Usuario.
User = True

Comenzamos con las elecciones que hace el usuario.

##### 1. Seleccionar el File

In [192]:
File_Path = t.Select_File(Explorer_Input_Title, Filetypes_Tuples_Input)

Selected file: C:/Users/tomas/Documents/Recortes/2024-08-13.txt

##### 1.1. Detectar idioma del File

Detectar las palabras y verificar.

__[HACER].__

- Función de análisis del idioma.

In [193]:
# File_Language = t.Language_File(File_Path)

##### 1.2. Procesamiento del File

Procesamiento y análisis del archivo .txt para que no cause problemas.

__[HACER].__

- Análisis del .txt en cuestión e indicando que no es compatible con el análisis.
- Procesamiento chiquito del .txt, como por ejemplo, borrar espacios antes y después.

In [194]:
# if File_Language:
    # File_Proccesed = t.Proccess_File(File_Path, File_Language)

    # if File_Proccesed = False:
    #    return File_Invalid_Alert

##### 2. Seleccionar formato de output

In [195]:
if User:
    Default_Output_Format = t.Choose_Option(Default_Output_Format_Options, 
                                     Default_Output_Format_Messages[0],
                                     Default_Output_Format_Messages[1],
                                     Default_Output_Format_Messages[2],
                                     Default_Output_Format_Messages[3])
    
    if Default_Output_Format:
        Output_Format = 'pdf'

if User == False or Default_Output_Format == False:
    Output_Format = t.Choose_Option(Output_Format_Options, 
                                    Output_Format_Messages[0],
                                    Output_Format_Messages[1],
                                    Output_Format_Messages[2],
                                    Output_Format_Messages[3])   
    
# ¿Son formateables los bloques?
Block_Formateable = ('pdf' in Output_Format or 'docx' in Output_Format or 'doc' in Output_Format)

¿Querés usar la configuración de salida por defecto?
1. True
2. False
Opción seleccionada: True

##### 3. Seleccionar la partición del output

In [196]:
if User:
    Default_Output_Partition = t.Choose_Option(Default_Output_Partition_Options, 
                                               Default_Output_Partition_Messages[0],
                                               Default_Output_Partition_Messages[1],
                                               Default_Output_Partition_Messages[2],
                                               Default_Output_Partition_Messages[3])
    
    if Default_Output_Partition:
        Output_Partition = True

if User == False or Default_Output_Partition == False:
    Output_Partition = t.Choose_Option(Output_Partition_Options, 
                                       Output_Partition_Messages[0],
                                       Output_Partition_Messages[1],
                                       Output_Partition_Messages[2],
                                       Output_Partition_Messages[3])

if Output_Partition:
    Output_Partition_Criterion = t.Choose_Option(Output_Partition_Criterion_Options, 
                                    Output_Partition_Criterion_Messages[0],
                                    Output_Partition_Criterion_Messages[1],
                                    Output_Partition_Criterion_Messages[2],
                                    Output_Partition_Criterion_Messages[3])

¿Querés usar la configuración de partición del archivo de salida por defecto?
1. True
2. False
Opción seleccionada: True

##### 4. Seleccionar path del output

In [197]:
if User:
    Default_Output_Path = t.Choose_Option(Default_Output_Path_Options, 
                                               Default_Output_Path_Messages[0],
                                               Default_Output_Path_Messages[1],
                                               Default_Output_Path_Messages[2],
                                               Default_Output_Path_Messages[3])
    
    if Default_Output_Path:
        Output_Path = 'c:/Users/tomas/Documents/Programación/Universidad/Patricionog/Highlights/'

if User == False or Default_Output_Path == False:
    Output_Path = t.Select_Directory(Explorer_Output_Title)

¿Querés usar la configuración de guardado del archivo de salida por defecto?
1. True
2. False
Opción seleccionada: True

##### 5. Decidir si se utilizan los Match por defecto

In [198]:
if User:
    Default_Match = t.Choose_Option(Default_Match_Options, 
                                    Default_Match_Messages[0],
                                    Default_Match_Messages[1],
                                    Default_Match_Messages[2],
                                    Default_Match_Messages[3])

# Agregar opciones por si no es usuario o si es pero no elige por defecto.

¿Querés usar la configuración de matchs y agrupamiento de highlights por defecto?
1. True
2. False
Opción seleccionada: True

##### 6. Decidir si se utiliza el Processing por defecto

In [199]:
if User:
    Default_Proccesing = t.Choose_Option(Default_Processing_Options, 
                                         Default_Processing_Messages[0],
                                         Default_Processing_Messages[1],
                                         Default_Processing_Messages[2],
                                         Default_Processing_Messages[3])

# Agregar opciones por si no es usuario o si es pero no elige por defecto.

¿Querés usar la configuración de procesamiento de los highlights por defecto?
1. True
2. False
Opción seleccionada: True

##### 7.1. Seleccionar estilo del bloque

In [200]:
if User and Block_Formateable:
    Default_Block_Style = t.Choose_Option(Default_Block_Style_Options, 
                                          Default_Block_Style_Messages[0],
                                          Default_Block_Style_Messages[1],
                                          Default_Block_Style_Messages[2],
                                          Default_Block_Style_Messages[3])
    
    Default_Naming = t.Choose_Option(Default_Naming_Options, 
                                          Default_Naming_Messages[0],
                                          Default_Naming_Messages[1],
                                          Default_Naming_Messages[2],
                                          Default_Naming_Messages[3])
    

if (User == False or Default_Block_Style == False) and Block_Formateable:
    
    Block_Style = t.Choose_Option(Block_Style_Options, 
                                       Block_Style_Messages[0],
                                       Block_Style_Messages[1],
                                       Block_Style_Messages[2],
                                       Block_Style_Messages[3])
    
    Highlight_Font_Style = t.Choose_Option(Highlight_Font_Style_Options, 
                                        Highlight_Font_Style_Messages[0],
                                        Highlight_Font_Style_Messages[1],
                                        Highlight_Font_Style_Messages[2],
                                        Highlight_Font_Style_Messages[3])

    # Highlight_Font = show_message("Fuente de Resaltado", Highlight_Font_Message)
    
    Subline_Font_Style = t.Choose_Option(Subline_Font_Style_Options, 
                                       Subline_Font_Style_Messages[0],
                                       Subline_Font_Style_Messages[1],
                                       Subline_Font_Style_Messages[2],
                                       Subline_Font_Style_Messages[3])
    
    Highlight_Font = input(Highlight_Font_Message)
    Subline_Font = input(Subline_Font_Message)

    Highlight_Color = input(Highlight_Color_Message)
    Subline_Color = input(Subline_Color_Message)

    Highlight_Font_Size = input(Highlight_Font_Size_Message)
    Subline_Font_Size = input(Subline_Font_Size_Message)

    Highlight_Align = t.Choose_Option(Highlight_Align_Options, 
                                       Highlight_Align_Messages[0],
                                       Highlight_Align_Messages[1],
                                       Highlight_Align_Messages[2],
                                       Highlight_Align_Messages[3])
    
    Subline_Align = t.Choose_Option(Subline_Align_Options, 
                                       Subline_Align_Messages[0],
                                       Subline_Align_Messages[1],
                                       Subline_Align_Messages[2],
                                       Subline_Align_Messages[3])

# Agregar opciones por si no es usuario o si es pero no elige por defecto.

¿Querés usar la configuración de estilo de los highlights por defecto?
1. True
2. False
Opción seleccionada: True
¿Querés usar la configuración de nombrado de archivos por defecto?
1. True
2. False
Opción seleccionada: True

##### 8. En caso de ser un output único, nombrarlo

In [201]:
if Output_Partition == False:
    Output_Name = input(Naming_Message)

NameError: name 'Output_Partition' is not defined

### __Etapa 2. Pantalla de bloques (P_Display)__

##### 1. Dataframe de notas

In [119]:
#if Default_Match == False:

# df total del recorte.
df = hg.Build_Df_Of_Highlights(File_Path)

df.head()

,Author,Book,Page,Day_Of_Week,Day,Month,Year,Hour,Highlight,Date
1010,David J. Chalmers,La mente consciente,9,Martes,13,8,2024,08:03:00,"En la práctica, por supuesto, no existe una se...",2024-08-13
1009,David J. Chalmers,La mente consciente,9,Martes,13,8,2024,08:02:00,"en principio, existen dos proyectos en la expl...",2024-08-13
1008,David J. Chalmers,La mente consciente,8,Martes,13,8,2024,07:48:00,esperamos que los fenómenos más básicos sean r...,2024-08-13
1006,David J. Chalmers,La mente consciente,8,Martes,13,8,2024,07:47:00,la superveniencia lógica elimina cualquier mis...,2024-08-13
1007,David J. Chalmers,La mente consciente,8,Martes,13,8,2024,07:47:00,"si la superveniencia lógica es válida, entonce...",2024-08-13

##### 2. Ordenamiento de los bloques por el usuario

In [120]:
# Estas dos opciones debería elegirlas el usuario.

# Opciones: ['Author', 'Book', 'Date']
Order_By = 'Author'
Ascending = False

df = fr.Sort_Columns(df, Order_By)

##### 3. Agrupamiento por condición que ponga el usuario

In [122]:
# Opciones: [None, 'Author', 'Book', 'Day_Of_Week', 'Date', 'Month', 'Year']
Group_By = 'Book'

if Group_By:
    Clippings = fr.Divide_DataFrames_By_Column(df, Group_By)

##### 4. Combinación de Blocks

##### 5. Eliminación de Blocks

##### 6. Dividir Blocks

##### 7. Cambio de nombre de Clippings

##### 8. Eliminar Clippings

### __3. Procesamiento del texto (H_Proccesing)__

In [ ]:
# Dejar pipí cucú los highlights.

df.loc[:, 'Highlight'] = df['Highlight'].apply(t.Procesar_Texto)

### __Etapa 4. Integración con Notion (P_Notion)__

In [41]:
# Elecciones del usuario.

Database_ID = '129a53d444454d63820814429c4fb691'

In [42]:
# Base de datos con autores e ID de las páginas en Notion dónde se pegan sus notas.
Base_Matcheos = []

In [43]:
# Extraer autores del recorte.
Autores = t.Extraer_Datos_Nota(File_Path, 'Ambos')

In [44]:
Autores = t.Extraer_Datos_Nota(File_Path, 'Autores')

In [45]:
# Matchear autores nuevos.
Base_Matcheos = t.Matcheo_Notas_Con_Base_Notion(Token, Autores, Database_ID, Base_Matcheos)

# Esta función vincula cada página de la base de datos con un elemento de la nota (libro o autor).
# Hay que generalizarla, porque solo funciona con autores. Tiene que funcionar con libros. 
# Y ver si hay alguna forma más.

Error al intentar acceder a la base de datos: 'str' object has no attribute 'databases'

TypeError: object of type 'NoneType' has no len()

In [9]:
# Lista de diccionarios con el autor y sus frases.

Lista_Diccionarios_Autores = t.Lista_De_Diccionarios_Por_Elemento_Padre(df, Autores, 'Autor', ['Libro', 'Highlight'])

In [10]:
# Columnas nuevas en el df.

df['ID_Autor'] = ''
df['ID_Libro'] = ''
df['Emoji'] = ''

In [11]:
# Armamos un df para los libros con sus respectivos ID.

df_Libros = pd.DataFrame()

for Autor in Autores:
    # Extraemos los ID de cada autor.
    for Match in Base_Matcheos:
        if Match['Autor'] == Autor:
            ID = Match['ID']

    # Formamos un df con las frases de cada autor.
    df_Frases_Autor = df[df['Autor'] == Autor]  

    # Formamos un df con los libros del autor.
    df_Libros_Autor = t.Obtener_IDs_y_Contenido_Bloques(Token, ID)

    # Eliminamos el número y los paréntesis.
    df_Libros_Autor['Contenido'] = df_Libros_Autor['Contenido'].apply(lambda x: t.Eliminar_Texto_Entre_Caracteres(x, '(', ')').strip())

    # Concatenar df1 y df2 verticalmente
    df_Libros = pd.concat([df_Libros, df_Libros_Autor], ignore_index=True)

    # Reordenar columnas.
    df_Libros = df_Libros[['Contenido', 'ID']]

In [12]:
# Pegar ID_Libro e ID_Autor en df.

# Creamos este df para poder transferir datos al df.
df_Matcheos = pd.DataFrame(Base_Matcheos)

df = t.Comparar_Df_y_Copiar(df, df_Libros, 'Libro', 'ID_Libro', 'Contenido', 'ID')
df = t.Comparar_Df_y_Copiar(df, df_Matcheos, 'Autor', 'ID_Autor', 'Autor', 'ID')

df[0:5]

,Autor,Libro,Pagina,Dia de la semana,Dia,Mes,Año,Hora,Highlight,ID_Autor,ID_Libro,Emoji
0,Lucio Anneo Séneca,Obras completas,108,Martes,18,Junio,2024,3:24,sobre los relojes públicos solía grabarse la i...,3b753b78-187f-414f-a78c-a9d106cca7fb,d96488ee-b603-42cb-97ed-8a3d8014f3d6,
1,Lucio Anneo Séneca,Obras completas,49,Martes,18,Junio,2024,3:25,«Es ridículo que te apresures a la muerte por ...,3b753b78-187f-414f-a78c-a9d106cca7fb,d96488ee-b603-42cb-97ed-8a3d8014f3d6,
2,Lucio Anneo Séneca,Séneca,49,Martes,18,Junio,2024,3:27,«¿Qué hay tan ridículo como suspirar por la mu...,3b753b78-187f-414f-a78c-a9d106cca7fb,,
3,Lucio Anneo Séneca,Séneca,49,Martes,18,Junio,2024,3:27,se nos ha de exhortar y fortalecer para este d...,3b753b78-187f-414f-a78c-a9d106cca7fb,,
4,Lucio Anneo Séneca,Séneca,50,Martes,18,Junio,2024,3:29,"»Es decir: me despertaré, dormiré; comeré, ten...",3b753b78-187f-414f-a78c-a9d106cca7fb,,

### __5. Generación del Output (P_End)__

In [15]:
# Generar pdf.
from fpdf import FPDF

In [ ]:
# Nombre del PDF final.
PDF_Name = 'PDF'

In [16]:
# Variables.

New_Font = 'ArialUnicode'
Pathway_New_Font = 'Fonts/arial-unicode-ms.ttf'

In [17]:
# Definir fuente del Highlight.

Font = New_Font
Fontsize = 12
Style = ''

In [18]:
# Propiedades de la celda.

Cell_Weight = 190
Cell_Height = 5
Cell_Align = 'L'

# Salto de línea después de la celda.
Cell_Line_Break = True

In [19]:
# Definir orden del highlight.

# Pueden elegir entre 6 órdenes.

# 1) 
# Highlight.
# Libro (Autor).

# 2) 
# Highlight.
# Autor (Libro).

# 3) 
# Highlight.
# Autor.

# 4) 
# Highlight.
# Libro.

# 5) 
# Highlight.
# Autor.
# Libro.

# 5) 
# Highlight.
# Libro.
# Autor.

Highlight_Style = 1

In [20]:
# Definir fuente de autor y libro.

# Autor.
Author_Font = Font
Author_Fontsize = 10
Autor_Align = 'L'
Author_Style = 'I'

# Libro.
Book_Font = Font
Book_Fontsize = 10
Book_Align = 'L'
Book_Style = 'I'

In [21]:
# Definir espacio.
Space_Between_Highlights = 8
Space_Between_Highlight_And_Author_Or_Book = 1.5

In [22]:
# Crea un objeto llamado 'PDF', instancia de la clase FPDF.
PDF = FPDF()

In [23]:
# Añadir fuente al pdf para que pueda leer caracteres especiales.
PDF.add_font(New_Font, '', Pathway_New_Font, uni=True) # Normal
PDF.add_font(New_Font, 'I', Pathway_New_Font, uni=True) # Italic
PDF.add_font(New_Font, 'B', Pathway_New_Font, uni=True) # Bold
PDF.add_font(New_Font, 'BI', Pathway_New_Font, uni=True) # Bold Italic

C:\Users\tomas\AppData\Local\Temp\ipykernel_17568\1237765908.py:2: DeprecationWarning: "uni" parameter is deprecated since v2.5.1, unused and will soon be removed
  PDF.add_font(New_Font, '', Pathway_New_Font, uni=True) # Normal
C:\Users\tomas\AppData\Local\Temp\ipykernel_17568\1237765908.py:3: DeprecationWarning: "uni" parameter is deprecated since v2.5.1, unused and will soon be removed
  PDF.add_font(New_Font, 'I', Pathway_New_Font, uni=True) # Italic
C:\Users\tomas\AppData\Local\Temp\ipykernel_17568\1237765908.py:4: DeprecationWarning: "uni" parameter is deprecated since v2.5.1, unused and will soon be removed
  PDF.add_font(New_Font, 'B', Pathway_New_Font, uni=True) # Bold
C:\Users\tomas\AppData\Local\Temp\ipykernel_17568\1237765908.py:5: DeprecationWarning: "uni" parameter is deprecated since v2.5.1, unused and will soon be removed
  PDF.add_font(New_Font, 'BI', Pathway_New_Font, uni=True) # Bold Italic

In [24]:
# Añadir una página al documento.
PDF.add_page()

In [25]:
# Establecer la fuente.
PDF.set_font(Font, size=Fontsize, style=Style)

In [26]:
for Index, Row in df.iterrows():
    # Agregar celda con la nota.
    PDF.set_font(Font, Style, Fontsize)
    PDF.multi_cell(Cell_Weight, Cell_Height, text=Row['Highlight'], ln=Cell_Line_Break, align=Cell_Align)

    # Espacio con la línea del autor o libro.
    PDF.ln(Space_Between_Highlight_And_Author_Or_Book)

    # AGREGAR LOS OTROS ESTILOS DESPUÉS.
    if Highlight_Style == 1:

        # Cambiar fuente, tamaño y estilo solo para esta celda
        PDF.set_font(Font, Author_Style, Author_Fontsize)
        PDF.cell(Cell_Weight, Cell_Height, text=f'{Row["Libro"]} ({Row["Autor"]})', ln=Cell_Line_Break, align=Autor_Align)
        
    # Espacio con el otro highlight.
    PDF.ln(Space_Between_Highlights)

C:\Users\tomas\AppData\Local\Temp\ipykernel_17568\2176654088.py:4: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  PDF.multi_cell(Cell_Weight, Cell_Height, text=Row['Highlight'], ln=Cell_Line_Break, align=Cell_Align)
C:\Users\tomas\AppData\Local\Temp\ipykernel_17568\2176654088.py:14: DeprecationWarning: The parameter "ln" is deprecated since v2.5.2. Instead of ln=True use new_x=XPos.LMARGIN, new_y=YPos.NEXT.
  PDF.cell(Cell_Weight, Cell_Height, text=f'{Row["Libro"]} ({Row["Autor"]})', ln=Cell_Line_Break, align=Autor_Align)

In [27]:
# Guarda el documento PDF en un archivo
PDF.output(f'C:/Users/tomas/Downloads/{PDF_Name}.pdf')